// Copyright (c) Cingulara LLC 2019 and Tutela LLC 2019. All rights reserved.
// Licensed under the GNU GENERAL PUBLIC LICENSE Version 3, 29 June 2007 license. See LICENSE file in the project root for full license information.
using System;
using MongoDB.Bson.Serialization.Attributes;
using MongoDB.Bson;
using openrmf_msg_score.Data;

namespace openrmf_msg_score.Models
{
    // this is the main record for this project
    // it records the INT of all counts for the types of 
    // status and category for vulnerabilities in a checklist
    public class Score
    {

        public Score () {
        }

        #region members
        [BsonId]
        // standard BSonId generated by MongoDb
        public ObjectId InternalId { get; set; }
        public ObjectId artifactId { get; set;}
        public string systemGroupId { get; set; }
        public string hostName { get; set;}
        public string stigType { get; set; }
        public string stigRelease { get; set; }
        public string title { get {
            return !string.IsNullOrEmpty(hostName)? hostName.Trim() + "-" + stigType.Trim() + "-" + stigRelease.Trim() : 
            "UnknownHost-" + stigType.Trim() + "-" + stigRelease.Trim();
        }}

        [BsonDateTimeOptions]
        public DateTime created { get; set; }
        [BsonDateTimeOptions]
        // attribute to gain control on datetime serialization
        public DateTime? updatedOn { get; set; }
        public Guid createdBy { get; set; }
        public Guid? updatedBy { get; set; }


        public int totalCat1Open { get; set; }
        public int totalCat1NotApplicable { get; set; }
        public int totalCat1NotAFinding { get; set; }
        public int totalCat1NotReviewed { get; set; }
        public int totalCat2Open { get; set; }
        public int totalCat2NotApplicable{ get; set; }
        public int totalCat2NotAFinding { get; set; }
        public int totalCat2NotReviewed { get; set; }
        public int totalCat3Open { get; set; }
        public int totalCat3NotApplicable { get; set; }
        public int totalCat3NotAFinding { get; set; }
        public int totalCat3NotReviewed { get; set; }

        public int totalOpen { get { return totalCat1Open + totalCat2Open + totalCat3Open;} }
        public int totalNotApplicable { get { return totalCat1NotApplicable + totalCat2NotApplicable + totalCat3NotApplicable;} }
        public int totalNotAFinding { get { return totalCat1NotAFinding + totalCat2NotAFinding + totalCat3NotAFinding;} }
        public int totalNotReviewed { get { return totalCat1NotReviewed + totalCat2NotReviewed + totalCat3NotReviewed;} }
        public int totalCat1 { get { return totalCat1NotAFinding + totalCat1NotApplicable + totalCat1NotReviewed + totalCat1Open;} }
        public int totalCat2 { get { return totalCat2NotAFinding + totalCat2NotApplicable + totalCat2NotReviewed + totalCat2Open;} }
        public int totalCat3 { get { return totalCat3NotAFinding + totalCat2NotApplicable + totalCat3NotReviewed + totalCat3Open;} }

        #endregion

        public async void SaveScore () {
            try {
                Settings s = new Settings();
                s.ConnectionString = Environment.GetEnvironmentVariable("MONGODBCONNECTION");
                s.Database = Environment.GetEnvironmentVariable("MONGODB");

                ScoreRepository _scoreRepo = new ScoreRepository(s);
                await _scoreRepo.AddScore(this);
            }
            catch (Exception ex) {
                Console.WriteLine(string.Format("Error Saving Score for {0}. {1}", this.title, ex.Message));
                throw ex;
            }
        }

        public async void UpdateScore () {
            try {
                Settings s = new Settings();
                s.ConnectionString = Environment.GetEnvironmentVariable("MONGODBCONNECTION");
                s.Database = Environment.GetEnvironmentVariable("MONGODB");

                ScoreRepository _scoreRepo = new ScoreRepository(s);
                await _scoreRepo.UpdateScore(this);
            }
            catch (Exception ex) {
                Console.WriteLine(string.Format("Error Updating Score for {0}. {1}", this.title, ex.Message));
                throw ex;
            }
        }

        public async void RemoveScore () {
            try {
                Settings s = new Settings();
                s.ConnectionString = Environment.GetEnvironmentVariable("MONGODBCONNECTION");
                s.Database = Environment.GetEnvironmentVariable("MONGODB");

                ScoreRepository _scoreRepo = new ScoreRepository(s);
                await _scoreRepo.RemoveScore(this.artifactId);
            }
            catch (Exception ex) {
                Console.WriteLine(string.Format("Error Removing Score for {0}. {1}", this.artifactId.ToString(), ex.Message));
                throw ex;
            }
        }

    }
}